/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MGTToken__factory } from "./MGTToken__factory";
export { VestingContract__factory } from "./VestingContract__factory";
