/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mgtTokenSol from "./MGTToken.sol";
export { Lock__factory } from "./Lock__factory";
export { Vault__factory } from "./Vault__factory";
