/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mgtTokenSol from "./MGTToken.sol";
export type { mgtTokenSol };
export type { Lock } from "./Lock";
export type { Vault } from "./Vault";
